# NOTE: Don't use `sudo` anywhere or the build will run on Travis's slower, outdated build system
language: java

matrix:
  fast_finish: true
  include:
    - os: linux
      jdk: oraclejdk8
    - os: osx
      osx_image: xcode8

cache:
  directories:
  - $HOME/.m2

script:
 - mvn clean verify